name: print_remover
description: print_remover remove all print() statement from the code.
version: 1.0.2
homepage:  https://github.com/cyclone-pk/print_remover

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
   args:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
